# config/packages/messenger.yaml
framework:
    messenger:
        enabled: false   # Désactive Messenger complètement
        transports: ~    # Pas de transport
        routing: ~       # Pas de routage
